# Generated by Django 5.2.17 on 2026-09-03 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT del cliente')),
                ('es_habitual', models.BooleanField(default=False, verbose_name='¿Cliente habitual?')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo electrónico del cliente')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono del cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del producto')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad disponible')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida', models.PositiveIntegerField(verbose_name='Cantidad vendida')),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de la venta')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la venta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.cliente', verbose_name='Cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.producto', verbose_name='Producto')),
            ],
        ),
    ]
